### ISSUE TITLE
Edn serialization should use pr-str

### ISSUE THREAD

**Issue by arichiardi** [colinkahn/todomvc-step#1]
Hi there!

Just noticed that [here](https://github.com/colinkahn/todomvc-step/blob/master/src/todomvc/db.cljs) you are using `str` but you should probably use `pr-str`.

I just wanted also to say that your library is great, not only it can be used in reframe but with any fsm that store its state as map!

I was actually thinking about this myself, I am glad I can now consider either using your lib or taking inspiration from it.

Nonetheless, thank you!

**Comment by colinkahn** [comment]
@arichiardi Thanks! So glad to hear you like the library. 

RE: the usage or `str`, that was from the original source code from the re-frame repo found here: https://github.com/Day8/re-frame/tree/master/examples/todomvc/

I would post an issue there as that is the "official" example and will have more eyes on it than this repo. My intent for this repo is to demonstrate validation using the step library with as little modification to the original code as possible.

Again, glad to hear you're excited about the library. I'm experimenting with generating graphs from the step forms. Here's one generated from the one found in this repo:

![todo-graph](https://user-images.githubusercontent.com/1444385/45689396-b5db9800-bb08-11e8-8bbc-ccf0848f2353.png)
